import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReactNode } from 'react';
import '../globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type RootLayoutProps = {
  children: ReactNode;
}

export default function RootLayout(props: RootLayoutProps) {
  const { children } = props;
  return (
    <html lang="en">
      <body className={inter.className}>
        GENERAL LAYOUT
        {children}
      </body>
    </html>
  )
}
